# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 659bc00779c4bd618d67a07a18053defe6719ed7cea4b54ebb97059a6227c61d62c02ac996852b8afe375c12d970babc69ad9c869c2a7972f12619284577be41

test:
  secret_key_base: c6a6a72884d84ef91931c2c134bae70c86dd6c3b48240ee0a88211a9be3dbaad6659b97297b77585e94102d4e1d63a0a030b3e2cbed7bbff88292f74356e3296

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
